spring.application.name=candidate-backend
logging.charset.console=UTF-8
spring.messages.encoding=UTF-8

app.cors.allowedOrigins=http://localhost:3000, http://localhost:3001

logging.level.org.springframework.security=DEBUG

# Dùng biến môi trường, nếu không có thì mặc định chạy localhost (để vẫn dev được ở máy)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.vnehhhbygyxigjckivbj.supabase.co:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Chienon@3107}

# Quan trọng: Lấy Port từ hệ thống Cloud cung cấp
server.port=${PORT:8083}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true