server:
  port: ${PORT:8083}

spring:
  servlet:
    contextPath:
  datasource:
    url: jdbc:postgresql://localhost:5433/candidate
#    url: jdbc:postgresql://host.docker.internal:5433/candidate
    username: postgres
    password: chienon@123
    driverClassName: org.postgresql.Driver
#    url: ${SPRING_DATASOURCE_URL:postgresql://postgres:rdlBlTKmpgJLCKddYtEaLomjbfQUexYV@postgres.railway.internal:5432/railway}
#    username: ${SPRING_DATASOURCE_USERNAME:postgres}
#    password: ${SPRING_DATASOURCE_PASSWORD:rdlBlTKmpgJLCKddYtEaLomjbfQUexYV}
#    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
jwt:
  signerKey: "Rrn3ID4ksu73c4cynwPKsLgtOx1X9vyg"

springdoc:
  swagger-ui:
    path: /swagger
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: false
    persist-authorization: true
# Test CI/CD