spring.application.name=candidate-backend
logging.charset.console=UTF-8
spring.messages.encoding=UTF-8

app.cors.allowedOrigins=http://localhost:3000, http://localhost:3001

logging.level.org.springframework.security=DEBUG