
# Secret Token
config.customerResetPasswordToken.secretKey = thisiskpcustomerresetpasswordsecretke
config.customerResetPasswordToken.alphabet = ABCDEFGHIJKLMNOPQRSTUVWXYZ123456789
config.customerResetPasswordToken.expirationTimeMin = 1440
config.customerResetPasswordToken.tokenLengthMin = 8

#Constants
config.webapp.https = 0 
#DateTime Format
config.date.format = dd-MM-yyyy
config.datetime.format = dd-MM-yyyy HH:mm
